apiVersion: apps/v1
kind: Deployment
metadata:
  name: mfe2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mfe2
  template:
    metadata:
      labels:
        app: mfe2
    spec:
      containers:
        - name: mfe2
          image: <replace_with_mfe2_image>:<tag>
          ports:
            - containerPort: 9002
      # Add any additional configuration needed, such as environment variables, volumes, etc.
---
apiVersion: v1
kind: Service
metadata:
  name: mfe2-service
spec:
  selector:
    app: mfe2
  ports:
    - protocol: TCP
      port: 9002
      targetPort: 9002
